package com.farukgenc.boilerplate.springboot.security.dto.resource;

import lombok.Data;

/**
 * DTO for resource creation responses.
 * Contains minimal information returned after creating a resource.
 * 
 * @author Generated
 */
@Data
public class CreateResourceResponse {

    /**
     * Resource unique identifier generated by JPA.
     */
    private Long id;

    /**
     * Resource name.
     */
    private String name;
}
